name: stg
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda-nvcc=12.1.66
  - cudatoolkit=11.8.0
  - folium=0.14.00
  - ipykernel=6.21.2
  - ipython=8.11.0
  - matplotlib-base=3.7.1
  - notebook=6.5.2
  - osmnx=1.3.0
  - pip=23.0.1 
  - plotly=5.13.1
  - python=3.10.9
  - shapely=2.0.1
  - tqdm=4.65.0
  - pip:
      - haversine==2.8.0
      - markdown==3.4.1
      - matplotlib==3.7.0
      - numpy~=1.22.4
      - pandas~=1.5.3
      - opacus==1.4.0
      - scikit-learn~=1.2.2
      - scipy==1.10.1
      - tabulate~=0.9.0
      - tensorboard~=2.13.0
      - tensorflow~=2.13.0
      - tensorrt~=8.5.3.1
      - torch==2.0.0
      - torchvision==0.15.1
      - utm==0.7.0
