name: GeoLife Pre-Processing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Dataset
        run: |
          mkdir -p data
          cd data
          wget https://download.microsoft.com/download/F/4/8/F4894AA5-FDBC-481E-9285-D5F8C4C4F039/Geolife%20Trajectories%201.3.zip
          unzip "Geolife Trajectories 1.3.zip"
          mv "Geolife Trajectories 1.3" geolife

      - name: Run Preprocessing
        run: |
          rm -r data/geolife_FIFTH-RING_5_60_200_TRUNCATE
          python3 -m stg.datasets.geolife

      - name: Run Unittests
        run: |
          python -m unittest test/test_geolife.py
        env:
          RUN_SLOW_TESTS: 'true'
          FORCE_TESTS: 'true'
