name: Unittests Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: stg
          environment-file: environment.yml
          auto-activate-base: false

      - name: Run unittests
        shell: bash -l {0}
        run: |
          conda activate stg
          python -m unittest discover test/
